import { mkdir, writeFile } from 'node:fs/promises';
import { Resvg } from '@resvg/resvg-js';
import { brandIcons, iconShape } from './brand-icons.mjs';

// Pre-render the glow: Stream Deck's SVG renderer does not consistently support blur filters.
export async function generateLogoArt(emit = writeFile) {
  const art = {};
  const images = {};
  const vectors = {};
  const darkVectors = {};
  const darkImages = {};
  for (const [provider, icon, color] of brandIcons) {
    art[provider] = {};
    if (icon.vector) vectors[provider] = icon.vector;
    if (icon.darkVector) darkVectors[provider] = icon.darkVector;
    if (icon.image) images[provider] = icon.image;
    if (icon.darkImage) darkImages[provider] = icon.darkImage;
    if (icon.noGlow) {
      art[provider].header = '';
      continue;
    }
    const haloShape = icon.image
      ? `<rect x="14" y="14" width="36" height="36" rx="9" fill="${color}"/>`
      : iconShape(icon, color, 'translate(14 14) scale(1.5)');
    const headerGlow = `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 64 64"><defs><filter id="halo" x="-100%" y="-100%" width="300%" height="300%"><feGaussianBlur stdDeviation="5"/></filter><filter id="inner" x="-100%" y="-100%" width="300%" height="300%"><feGaussianBlur stdDeviation="2"/></filter></defs><g filter="url(#halo)">${haloShape}</g><g filter="url(#inner)" opacity="0.7">${haloShape}</g></svg>`;
    art[provider].header =
      `data:image/png;base64,${new Resvg(headerGlow).render().asPng().toString('base64')}`;
  }
  await mkdir('src/generated', { recursive: true });
  // Providers with original app artwork use it as the header image instead of a vector path.
  await emit(
    'src/generated/logo-art.ts',
    `// Generated by scripts/logo-art.mjs; rebuild to regenerate.\nexport const logoArt = ${JSON.stringify(art)} as const;\nexport const iconVectors: Partial<Record<string, string>> = ${JSON.stringify(vectors)};\nexport const darkIconVectors: Partial<Record<string, string>> = ${JSON.stringify(darkVectors)};\nexport const iconImages: Partial<Record<string, string>> = ${JSON.stringify(images)};\nexport const darkIconImages: Partial<Record<string, string>> = ${JSON.stringify(darkImages)};\n`
  );
}
